baseURL = 'https://chenjiung.github.io/'
languageCode = 'zh-cn'
title = "chenjiuling - åœ¨é˜…è¯»ä¸­é‡è§è‡ªå·±"
theme = "gitHub-style"

[params]
  author = "chenjiuling"
  description = "åœ¨é˜…è¯»ä¸­é‡è§è‡ªå·±"
  github = "chenjiuling"
  facebook = ""
  twitter = ""
  linkedin = ""
  instagram = ""
  tumblr = ""
  email = "chenjie411524@outlook.com"
  url = "https://github.com/chenjiuling"
  keywords = "blog, android"
  rss = false
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  favicon = "/images/github.png"
  location = "China"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]